# Generated by Django 3.2.8 on 2021-10-31 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('date',)},
        ),
    ]
