# Generated by Django 3.2.8 on 2021-11-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0004_alter_post_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
